#!/usr/bin/env bash
# onboarding.sh — First-run setup wizard

_gmt_onboarding() {
  local init_file="${GMT_DIR}/data/.initialized"
  [[ -f "$init_file" ]] && return 0

  echo ""
  draw_box "$(printf '%s\n\n%s' "  ☀ Good Morning Terminal" "  ${L_ONBOARD_WELCOME}")"
  echo ""

  # Step 1: Language
  echo "  Step 1/4 · ${L_ONBOARD_LANG_ASK}"
  echo "    [1] 한국어"
  echo "    [2] English"
  echo "    [3] 日本語"
  echo "    [4] 中文"
  printf "    ▸ "
  read -r lang_choice
  case "$lang_choice" in
    1) GMT_LANG="ko" ;;
    2) GMT_LANG="en" ;;
    3) GMT_LANG="ja" ;;
    4) GMT_LANG="zh" ;;
    *) GMT_LANG="en" ;;
  esac

  # Reload language pack immediately
  _gmt_load_lang
  echo ""

  # Step 2: Name
  echo "  Step 2/4 · ${L_ONBOARD_NAME_ASK}"
  printf "  $(printf "$L_ONBOARD_NAME_DEFAULT" "$USER")\n"
  printf "    ▸ "
  read -r user_name
  GMT_USERNAME="${user_name:-$USER}"
  echo ""

  # Step 3: Weather
  echo "  Step 3/4 · ${L_ONBOARD_WEATHER_ASK} [Y/n]"
  printf "    ▸ "
  read -r weather_yn
  if [[ "${weather_yn,,}" != "n" ]]; then
    GMT_WEATHER_ENABLED=true
    echo "  ${L_ONBOARD_WEATHER_CITY} (Enter = Seoul)"
    printf "    ▸ "
    read -r city
    GMT_WEATHER_CITY="${city:-Seoul}"
  else
    GMT_WEATHER_ENABLED=false
  fi
  echo ""

  # Write config.sh
  cat > "${GMT_DIR}/config.sh" << GMTEOF
#!/usr/bin/env bash
# config.sh — GMT user configuration (generated by onboarding)

GMT_USERNAME="${GMT_USERNAME}"
GMT_LANG="${GMT_LANG}"
GMT_WEATHER_ENABLED=${GMT_WEATHER_ENABLED}
GMT_WEATHER_CITY="${GMT_WEATHER_CITY}"
GMT_WEATHER_CACHE_TTL=1800
GMT_MODULES="greeting projects sysinfo todos activity"
GMT_PROJECTS_COUNT=5
GMT_ACTIVITY_WEEKS=12
GMTEOF

  # Step 4: Done
  echo "  Step 4/4"
  echo ""
  local done_msg="$(printf '%s\n%s\n\n%s\n%s\n%s\n%s' \
    "  ${L_ONBOARD_DONE}" \
    "  ${L_ONBOARD_DONE_DESC}" \
    "  · gmt add \"task\"   $(echo "${L_HELP_COMMANDS[1]}" | sed 's/gmt add.*  //')" \
    "  · gmt go 1         $(echo "${L_HELP_COMMANDS[5]}" | sed 's/gmt go.*  //')" \
    "  · gmt config       $(echo "${L_HELP_COMMANDS[6]}" | sed 's/gmt config.*  //')" \
    "  · gmt help         $(echo "${L_HELP_COMMANDS[7]}" | sed 's/gmt help.*  //')")"
  draw_box "$done_msg"
  echo ""
  printf "  ${C_DIM}%s${C_RESET}\n" "$L_ONBOARD_TIP"
  echo ""

  # Mark initialization complete
  touch "$init_file"

  # Show home screen
  _gmt_render_home
}
