#!/usr/bin/env bash
# config.sh — GMT user configuration (generated by onboarding)

GMT_USERNAME="찬님"
GMT_LANG="en"
GMT_WEATHER_ENABLED=false
GMT_WEATHER_CITY="Seoul"
GMT_WEATHER_CACHE_TTL=1800
GMT_MODULES="greeting projects sysinfo todos activity"
GMT_PROJECTS_COUNT=5
GMT_ACTIVITY_WEEKS=12
